export const levels = [
  {name: "Bazza's Blockade Cave", id: "1A", address: "3D0599", type: 6},
  {name: "Fish Food Frenzy Cave", id: "1B", address: "3D05B0", type: 6},
  {name: "Floodlit Fish Cave", id: "1C", address: "3D05C7", type: 6},
  {name: "Belcha's Barn", id: "1D", address: "3D05DE", type: 3},
  {name: "Arich's Ambush", id: "1E", address: "3D05FF", type: 3},
  {name: "Squirt's Showdown", id: "1F", address: "3D0616", type: 3},
  {name: "KAOS Karnage", id: "20", address: "3D062D", type: 3},
  {name: "Bleak's House", id: "21", address: "3D0649", type: 3},
  {name: "Barbos' Barrier", id: "22", address: "3D0660", type: 3},
  {name: "Kastle KAOS", id: "23", address: "3D067C", type: 3},
  {name: "Knautilus", id: "24", address: "3D0698", type: 3},
  {name: "Lakeside Limbo", id: "25", address: "3D06AF", type: 1},
  {name: "Kreeping Klasps", id: "26", address: "3D06E5", type: 1},
  {name: "Tidal Trouble", id: "27", address: "3D071B", type: 1},
  {name: "Doorstop Dash", id: "28", address: "3D0751", type: 1},
  {name: "Squeals On Wheels", id: "29", address: "3D078C", type: 1},
  {name: "Murky Mill", id: "2A", address: "3D07C2", type: 1},
  {name: "Skidda's Row", id: "2B", address: "3D07F8", type: 1},
  {name: "Lemguin Lunge", id: "2C", address: "3D082E", type: 1},
  {name: "Tearaway Toboggan", id: "2D", address: "3D0864", type: 1},
  {name: "Ripsaw Rage", id: "2E", address: "3D0895", type: 1},
  {name: "Springin' Spiders", id: "2F", address: "3D08CB", type: 1},
  {name: "Barrel Shield Bust-Up", id: "30", address: "3D08FC", type: 1},
  {name: "Swoopy Salvo", id: "31", address: "3D0932", type: 1},
  {name: "Riverside Race", id: "32", address: "3D096A", type: 1},
  {name: "Lightning Lookout", id: "33", address: "3D09AA", type: 1},
  {name: "Bobbing Barrel Brawl", id: "34", address: "3D09DB", type: 1},
  {name: "Bazza's Blockade", id: "35", address: "3D0A0C", type: 1},
  {name: "Fish Food Frenzy", id: "36", address: "3D0A43", type: 1},
  {name: "Floodlit Fish", id: "37", address: "3D0A7A", type: 1},
  {name: "Rocket Barrel Ride", id: "38", address: "3D0AB1", type: 1},
  {name: "Tracker Barrel Trek", id: "39", address: "3D0AE2", type: 1},
  {name: "Barrel Drop Bounce", id: "3A", address: "3D0B13", type: 1},
  {name: "Fire Ball Frenzy", id: "3B", address: "3D0B44", type: 1},
  {name: "Blazing Bazukas", id: "3C", address: "3D0B75", type: 1},
  {name: "Krack-Shot Kroc", id: "3D", address: "3D0BA6", type: 1},
  {name: "Low-G Labyrinth", id: "3E", address: "3D0BD7", type: 1},
  {name: "Poisonous Pipeline", id: "3F", address: "3D0C0D", type: 1},
  {name: "Demolition Drainpipe", id: "40", address: "3D0C3E", type: 1},
  {name: "Krevice Kreepers", id: "41", address: "3D0C6F", type: 1},
  {name: "Kong-Fused Cliffs", id: "42", address: "3D0CA0", type: 1},
  {name: "Ropey Rumpus", id: "43", address: "3D0CD1", type: 1},
  {name: "Buzzer Barrage", id: "44", address: "3D0D02", type: 1},
  {name: "Pot-Hole Panic", id: "45", address: "3D0D33", type: 1},
  {name: "Creepy Caverns", id: "46", address: "3D0D64", type: 1},
  {name: "Koindozer Klamber", id: "47", address: "3D0D95", type: 1},
  {name: "Konveyor Rope Klash", id: "48", address: "3D0DC6", type: 1},
  {name: "Stampede Sprint", id: "49", address: "3D0DF7", type: 1},
  {name: "Criss Cross Cliffs", id: "4A", address: "3D0E2F", type: 1},
  {name: "Tyrant Twin Tussle", id: "4B", address: "3D0E60", type: 1},
  {name: "Rocket Rush", id: "4C", address: "3D0E98", type: 1},
  {name: "Lakeside Limbo Bonus 1", id: "50", address: "3D0ED8", type: 2},
  {name: "Lakeside Limbo Bonus 2", id: "51", address: "3D0EF1", type: 2},
  {name: "Doorstop Dash Bonus 1", id: "52", address: "3D0F0A", type: 2},
  {name: "Doorstop Dash Bonus 2", id: "53", address: "3D0F23", type: 2},
  {name: "Tidal Trouble Bonus 1", id: "54", address: "3D0F3C", type: 2},
  {name: "Tidal Trouble Bonus 2", id: "55", address: "3D0F55", type: 2},
  {name: "Skidda's Row Bonus 1", id: "56", address: "3D0F6E", type: 2},
  {name: "Skidda's Row Bonus 2", id: "57", address: "3D0F87", type: 2},
  {name: "Squeals On Wheels Bonus 1", id: "58", address: "3D0FA0", type: 2},
  {name: "Squeals On Wheels Bonus 2", id: "59", address: "3D0FB9", type: 2},
  {name: "Barrel Shield Bust-Up Bonus 1", id: "5A", address: "3D0FD2", type: 2},
  {name: "Barrel Shield Bust-Up Bonus 2", id: "5B", address: "3D0FEB", type: 2},
  {name: "Riverside Race Bonus 1", id: "5C", address: "3D1004", type: 2},
  {name: "Riverside Race Bonus 2", id: "5D", address: "3D101D", type: 2},
  {name: "Murky Mill Bonus 1", id: "5E", address: "3D1036", type: 2},
  {name: "Murky Mill Bonus 2", id: "5F", address: "3D104F", type: 2},
  {name: "Springin' Spiders Bonus 1", id: "60", address: "3D1068", type: 2},
  {name: "Springin' Spiders Bonus 2", id: "61", address: "3D1081", type: 2},
  {name: "Lightning Lookout Bonus 1", id: "62", address: "3D109A", type: 2},
  {name: "Lightning Lookout Bonus 2", id: "63", address: "3D10B3", type: 2},
  {name: "Bazza's Blockade Bonus 1", id: "64", address: "3D10CC", type: 2},
  {name: "Bazza's Blockade Bonus 2", id: "65", address: "3D10E5", type: 2},
  {name: "Rocket Barrel Ride Bonus 1", id: "66", address: "3D10FE", type: 2},
  {name: "Rocket Barrel Ride Bonus 2", id: "67", address: "3D1117", type: 2},
  {name: "Kreeping Klasps Bonus 1", id: "68", address: "3D1130", type: 2},
  {name: "Kreeping Klasps Bonus 2", id: "69", address: "3D1149", type: 2},
  {name: "Tracker Barrel Trek Bonus 1", id: "6A", address: "3D1162", type: 2},
  {name: "Tracker Barrel Trek Bonus 2", id: "6B", address: "3D117B", type: 2},
  {name: "Fish Food Frenzy Bonus 1", id: "6C", address: "3D1194", type: 2},
  {name: "Fish Food Frenzy Bonus 2", id: "6D", address: "3D11AD", type: 2},
  {name: "Fire Ball Frenzy Bonus 1", id: "6E", address: "3D11C6", type: 2},
  {name: "Fire Ball Frenzy Bonus 2", id: "6F", address: "3D11DF", type: 2},
  {name: "Demolition Drainpipe Bonus 1", id: "70", address: "3D11F8", type: 2},
  {name: "Demolition Drainpipe Bonus 2", id: "71", address: "3D1211", type: 2},
  {name: "Ripsaw Rage Bonus 1", id: "72", address: "3D122A", type: 2},
  {name: "Ripsaw Rage Bonus 2", id: "73", address: "3D1243", type: 2},
  {name: "Blazing Bazukas Bonus 1", id: "74", address: "3D125C", type: 2},
  {name: "Blazing Bazukas Bonus 2", id: "75", address: "3D1275", type: 2},
  {name: "Low-G Labyrinth Bonus 1", id: "76", address: "3D128E", type: 2},
  {name: "Low-G Labyrinth Bonus 2", id: "77", address: "3D12A7", type: 2},
  {name: "Krevice Kreepers Bonus 1", id: "78", address: "3D12C0", type: 2},
  {name: "Krevice Kreepers Bonus 2", id: "79", address: "3D12D9", type: 2},
  {name: "Tearaway Toboggan Bonus 1", id: "7A", address: "3D12F2", type: 2},
  {name: "Tearaway Toboggan Bonus 2", id: "7B", address: "3D130B", type: 2},
  {name: "Barrel Drop Bounce Bonus 1", id: "7C", address: "3D1324", type: 2},
  {name: "Barrel Drop Bounce Bonus 2", id: "7D", address: "3D133D", type: 2},
  {name: "Krack-Shot Kroc Bonus 1", id: "7E", address: "3D1356", type: 2},
  {name: "Krack-Shot Kroc Bonus 2", id: "7F", address: "3D136F", type: 2},
  {name: "Lemguin Lunge Bonus 1", id: "80", address: "3D1388", type: 2},
  {name: "Lemguin Lunge Bonus 2", id: "81", address: "3D13A1", type: 2},
  {name: "Buzzer Barrage Bonus 1", id: "82", address: "3D13BA", type: 2},
  {name: "Buzzer Barrage Bonus 2", id: "83", address: "3D13D3", type: 2},
  {name: "Kong-Fused Cliffs Bonus 1", id: "84", address: "3D13EC", type: 2},
  {name: "Kong-Fused Cliffs Bonus 2", id: "85", address: "3D1405", type: 2},
  {name: "Floodlit Fish Bonus 1", id: "86", address: "3D141E", type: 2},
  {name: "Floodlit Fish Bonus 2", id: "87", address: "3D1437", type: 2},
  {name: "Pot-Hole Panic Bonus 1", id: "88", address: "3D1450", type: 2},
  {name: "Pot-Hole Panic Bonus 2", id: "89", address: "3D1469", type: 2},
  {name: "Ropey Rumpus Bonus 1", id: "8A", address: "3D1482", type: 2},
  {name: "Ropey Rumpus Bonus 2", id: "8B", address: "3D149B", type: 2},
  {name: "Koindozer Klamber Bonus 1", id: "8C", address: "3D14B4", type: 2},
  {name: "Koindozer Klamber Bonus 2", id: "8D", address: "3D14CD", type: 2},
  {name: "Creepy Caverns Bonus 1", id: "8E", address: "3D14E6", type: 2},
  {name: "Creepy Caverns Bonus 2", id: "8F", address: "3D14FF", type: 2},
  {name: "Bobbing Barrel Brawl Bonus 1", id: "90", address: "3D1518", type: 2},
  {name: "Bobbing Barrel Brawl Bonus 2", id: "91", address: "3D1531", type: 2},
  {name: "Konveyor Rope Klash Bonus 1", id: "92", address: "3D154A", type: 2},
  {name: "Konveyor Rope Klash Bonus 2", id: "93", address: "3D1563", type: 2},
  {name: "Poisonous Pipeline Bonus 1", id: "94", address: "3D157C", type: 2},
  {name: "Poisonous Pipeline Bonus 2", id: "95", address: "3D1595", type: 2},
  {name: "Swoopy Salvo Bonus 1", id: "96", address: "3D15AE", type: 2},
  {name: "Swoopy Salvo Bonus 2", id: "97", address: "3D15C7", type: 2},
  {name: "Swoopy Salvo Bonus 3", id: "98", address: "3D15E0", type: 2},
  {name: "Criss Cross Cliffs Bonus 1", id: "99", address: "3D15F9", type: 2},
  {name: "Criss Cross Cliffs Bonus 2", id: "9A", address: "3D1612", type: 2},
  {name: "Tyrant-Twin Tussle Bonus 1", id: "9B", address: "3D162B", type: 2},
  {name: "Tyrant-Twin Tussle Bonus 2", id: "9C", address: "3D1644", type: 2},
  {name: "Tyrant-Twin Tussle Bonus 3", id: "9D", address: "3D165D", type: 2},
  {name: "Stampede Sprint Bonus 1", id: "9E", address: "3D1676", type: 2},
  {name: "Stampede Sprint Bonus 2", id: "9F", address: "3D168F", type: 2},
  {name: "Stampede Sprint Bonus 3", id: "A0", address: "3D16A8", type: 2}
];

export const bgms = {
  0: "No change (?)",
  6: "Water World",
  7: "Hot Pursuit",
  8: "Nuts & Bolts",
  10: "Cascade Capers",
  11: "Treetop Tumble",
  12: "Boss Boogie (Arich/Bleak)",
  14: "Mill Fever",
  15: "Stilt Village",
  16: "Enchanted Riverbank",
  23: "Frosty Frolics",
  25: "Pokey Pipes",
  26: "Big Boss Blues (K. Rool 2)",
  28: "Rocket Run",
  29: "Jungle Jitter",
  30: "Cavern Caprice",
  31: "Boss Boogie (Belcha/Barbos)",
  33: "Rockface Rumble",
  38: "Nuts & Bolts (Krack-Shot Kroc)",
  39: "Big Boss Blues (K. Rool 1)",
  40: "Boss Boogie (KAOS/Squirt)",
  41: "Cavern Caprice (Pot Hole Panic)",
  73: "Swanky's Sideshow"
};

export const levelTypes = {
  1: "Regular Stage",
  2: "Bonus Stage",
  3: "Boss",
  4: "Unused?",
  5: "Swanky's Sideshow",
  6: "Water Stage Exit Room"
}

export const bonusTypes = {
  1: "Find the Coin",
  2: "Bash the Baddies",
  3: "Collect the Stars",
  4: "Grab the Bananas"
}